### ISSUE TITLE
[8.0] Rights problem after installing product_lifecycle when creating products

### ISSUE THREAD

**Issue by johannbelet** [Vauxoo/addons-vauxoo#1024]
### Odoo message

```
Access Denied

The requested operation cannot be completed due to security restrictions. Please contact your system administrator.

(Document type: Product Template, Operation: write)
```

**Comment by johannbelet** [comment]
Sorry, this message is a bit empty.

Here is the configuration:

Sales: Manager
Project: Nothing
Knowledge: User
Warehouse: Manager
Manufacturing: Manager
Accounting & Finance: Invoicing & Payments
Purchases: Manager
Purchase Requisition: Nothing
Human Resources: Manager
Marketing: Nothing
Website: Manage Website and qWeb view
Sharing: User

The action was tried from Warehouse -> Products -> Create button

**Comment by osvalr** [comment]
Hi @johannbelet, could you please follow this [template](https://raw.githubusercontent.com/OCA/maintainer-tools/master/.github/ISSUE_TEMPLATE.md) to describe your issue? (you can re-edit it). 

Thank you

**Comment by johannbelet** [comment]
### Milestone (Odoo version)
- 8.0

### Module(s)
- product_lifecycle (addons-vauxoo/product_lifecycle [branch 8.0])

### Steps to reproduce
1. Install module product_lifecycle and dependancies
2. Set Manager rights on Sales, Purchase, Warehouse, Manufacturing
3. Create a product (product template)

### Current behavior

Access Denied

The requested operation cannot be completed due to security restrictions. Please contact your system administrator.

(Document type: Product Template, Operation: write)

### Expected behavior

Product created successfully

**Comment by nhomar** [comment]
hello Thanks for take care of make a proper issue.

If you see here:

https://github.com/Vauxoo/addons-vauxoo/blob/8.0/product_lifecycle/security/product_security.xml

The domain:

```
[('product_manager','=', user.id)]
```

Indicates that only the product manager can edit a product.

Only set the proper product manager into the product and all will works properly.

Note: If you have developments that need write permissions, either use sudo in the code or extend this domain with your needs.

**Comment by johannbelet** [comment]
Thank you for your time and answer.
Didn't see the field product manager...

Ok problem solved
