### ISSUE TITLE
[product_available_by_warehouse] domain of routes must be routes in sale order line

### ISSUE THREAD

**Issue by JulioSerna** [Vauxoo/addons-vauxoo#1054]
When use **Show message** to see product available the domain in route are modfied but the domain must be consider the router that only are available in sale order line
## with **Show message**

![sale_order_route_domain](https://cloud.githubusercontent.com/assets/7595505/18285974/5172e64a-7436-11e6-9141-b081ae35f818.png)

---
## without **Show message**

![sale_order_route](https://cloud.githubusercontent.com/assets/7595505/18285981/5a53e9c6-7436-11e6-8a7a-64dfe676f1a5.png)
- Expected behavior

Shows routes available in **sale order line** and there are routes from locations usage **supplier** like **Dropshipping** that must be available as well

**Comment by suniagajose** [comment]
I got it @JulioSerna... 

i will work on the following TODO list :
- [x] avoid route_ids domain in 'show message' onchange.
- [x] use sudo in warehouse search to show always the same info no matter what permission has the user.
- [x] swap positions between show_message field and product_id field

If i forgot anything or you have a additional requirement, please share it...

Regards,
