### ISSUE TITLE
Error en Reintegrar Factura con account_voucher_tax instalado en el sistema

### ISSUE THREAD

**Issue by jesusmezadme** [Vauxoo/addons-vauxoo#108]
Hola...

Hemos estado realizando pruebas de Reintegros de Facturas y hemos notado que cuando tenemos instalado el módulo de "account_voucher_tax" no nos permite reintegrar la factura, en cambio cuando no lo tenemos instalado sí nos permite hacerlo. Las dos formas de reintegro con las que hemos notado los problemas son con "Saldar: crea la Nota de Crédito y concilia" y con "Modificar: crea la Nota de Crédito, concilia y crea una nueva Factura borrador".

Este es el error que nos arroja:

Server Traceback (most recent call last):
  File "/home/jesusmeza/odoo/7.0/server/modules/web/session.py", line 89, in send
    return openerp.netsvc.dispatch_rpc(service_name, method, args)
  File "/home/jesusmeza/odoo/7.0/server/openerp/netsvc.py", line 296, in dispatch_rpc
    result = ExportService.getService(service_name).dispatch(method, params)
  File "/home/jesusmeza/odoo/7.0/server/openerp/service/web_services.py", line 632, in dispatch
    res = fn(db, uid, _params)
  File "/home/jesusmeza/odoo/7.0/server/openerp/osv/osv.py", line 190, in execute_kw
    return self.execute(db, uid, obj, method, *args, *_kw or {})
  File "/home/jesusmeza/odoo/7.0/server/openerp/osv/osv.py", line 132, in wrapper
    return f(self, dbname, _args, *_kwargs)
  File "/home/jesusmeza/odoo/7.0/server/openerp/osv/osv.py", line 199, in execute
    res = self.execute_cr(cr, uid, obj, method, _args, *_kw)
  File "/home/jesusmeza/odoo/7.0/server/openerp/osv/osv.py", line 187, in execute_cr
    return getattr(object, method)(cr, uid, _args, *_kw)
  File "/home/jesusmeza/odoo/7.0/server/modules/account/wizard/account_invoice_refund.py", line 232, in invoice_refund
    return self.compute_refund(cr, uid, ids, data_refund, context=context)
  File "/home/jesusmeza/odoo/7.0/server/modules/account/wizard/account_invoice_refund.py", line 183, in compute_refund
    writeoff_acc_id=inv.account_id.id
  File "/home/jesusmeza/odoo/7.0/server/modules/account_voucher_tax/account_voucher.py", line 588, in reconcile
    if context.get('apply_round', False):
AttributeError: 'NoneType' object has no attribute 'get'

Además esta es la pantalla donde se manda reintegrar la Factura:

![captura de pantalla de 2015-02-06 17 07 40](https://cloud.githubusercontent.com/assets/8386554/6089687/f7eb6748-ae23-11e4-92de-cdded8af4ba5.png)

Si se requiere de más información, estaré disponible a través del email.

Saludos =)

**Comment by moylop260** [comment]
@jesusmezadme 
Puedes darnos los sha de las versiones en las que estás usando este branch, por favor.
Así como el sha de la versión del branch de odoo.

También nos puedes dar el `git rev-parse --abbrev-ref HEAD` y el `git log --oneline -1` del branch de odoo y de addons-vauxoo.

**Comment by jesusmezadme** [comment]
Hola que tal... disculpen la tardanza...

Lo primero no sé cómo sacarlo, estuve investigando y lo único que encontré para sacar el SHA es con git rev-parse HEAD. Si me equivoco entonces ¿podrían indicarme cómo sacarlo por favor?

account_voucher_tax git rev-parse HEAD: "85214ea52b17e7feb79ac7d5c8bc341d2d9294a0"

Lo segundo:

Odoo git rev-parse --abbrev-ref HEAD: "7.0"
Odoo git log --oneline -1: "0b7db55 [FIX] share: action params in url is action, not action_id"

addons-vauxoo git rev-parse --abbrev-ref HEAD: "7.0"
addons-vauxoo git log --oneline -1: "85214ea Merge pull request #103 from nhomar/7.0-project-issue-extention-add"

Cualquier duda o comentario estoy a la orden. Saludos

**Comment by JulioSerna** [comment]
Hola que tal @jesusmezadme 

En breve estaremos pasando una PR para que se resuelva este error,

Saludos.

**Comment by jesusmezadme** [comment]
Enterado @JulioSerna 

Muchas gracias, si ocupan algo más me avisan.

Saludos

**Comment by JulioSerna** [comment]
@moylop260 

Las pruebas de esta PR fueron probadas en este runbot,
http://runbot.vauxoo.com/runbot/team/oml-v2-17?testing=1&running=1&done=1&limit=10000&pending=1#7_0-oml-v2%20%5BVauxoo_addons-vauxoo_118%5D

Puedes darme tu +1 para este cambio

**Comment by moylop260** [comment]
@JulioSerna 
Can you link PR to this fix, please?

@jesusmezadme 
Can you test it with this PR, please:
https://github.com/Vauxoo/addons-vauxoo/pull/118

**Comment by JulioSerna** [comment]
@moylop260 

La  PR ya esta asociada a este Issue

**Comment by jesusmezadme** [comment]
@JulioSerna y @moylop260 
Gracias por el apoyo.

@moylop260 
Disculpa pero ¿cómo podemos testear ese PR?... intentamos hacer git pull sobre el módulo pero nos dice que ya está actualizado, ¿será que tenemos que cambiar a alguna rama en especial?

**Comment by moylop260** [comment]
@jesusmezadme 
Tendrás que probar con el siguiente PR:
https://github.com/Vauxoo/addons-vauxoo/pull/118

Si no tienes conocimientos sobre git y github, revisa el cambio que se hizo aquí: https://github.com/Vauxoo/addons-vauxoo/pull/118/files
Para que aplique el parche en local, es decir, intenta cambiar tus archivos locales, de manera manual, tal cual como se propone en el PR, y nos comentas si quedó resuelto.

**Comment by jesusmezadme** [comment]
@moylop260 
Entendido, tendré que hacer la modificación sobre mi archivo local, en cuanto lo pruebe les aviso para notificar sobre el resultado obtenido. Estaremos en contacto

**Comment by jesusmezadme** [comment]
@moylop260  y @JulioSerna 
Hemos realizado las pruebas con la modificación local del archivo y obtuvimos resultados satisfactorios. Funcionó correctamente, ya no marca error.

Supongo ahora se procederá a subir la modificación para poder descargarla en producción.

Cualquier duda o comentario estoy a la orden. Saludos y que tengan un excelente día.

**Comment by moylop260** [comment]
merged https://github.com/Vauxoo/addons-vauxoo/pull/118
