### ISSUE TITLE
[8.0] Product Lifecycle module description do not properly show in odoo apps

### ISSUE THREAD

**Issue by zaoral** [Vauxoo/addons-vauxoo#1150]
**Current Behavior**

Odoo Apps [page](https://apps.openerp.com/apps/modules/8.0/product_lifecycle/) for product_lifecycle module.

![image](https://cloud.githubusercontent.com/assets/7593953/21703672/7aa6365a-d379-11e6-9aa4-443869c97589.png)

**Expected Behavior**

Show the module description, I enter inside a odoo instance, and look inside the module tab and the next screenshot is what I found: We need this description appears in the odoo apps page.

![image](https://cloud.githubusercontent.com/assets/7593953/21703742/ef95343e-d379-11e6-93b8-579a4af55524.png)

**Comment by nhomar** [comment]
This will not be solved, and will be deprecated for 10 (or improved)
