### ISSUE TITLE
partner_credit_limit V10 credit limit does nothing

### ISSUE THREAD

**Issue by rzgarabedi** [Vauxoo/addons-vauxoo#1158]
hi i installed your module today and for example i set a costumer credit limit of 10000 IRT .
IRT is iran toman and i create this currency by myself when i set credit limit to a number it didnt show any currency field in front of it so after confirming invoice even if the amount is higher than the credit limit the sale can be invoiced and no error showing am i missing some thing here? any help is much appreciated.

**Comment by nhomar** [comment]
The credit limit must be loaded in the currency of the company, let me know if it helps.

regards.

**Comment by rzgarabedi** [comment]
im only using one currency right now. how to load credit limit in company currency?

**Comment by rzgarabedi** [comment]
i couldnt find this can you plz prodive me more detail on how to setup credit limit?
