### ISSUE TITLE
[stock_account_unfuck] Create a nice Documentation to show on Module Form

### ISSUE THREAD

**Issue by hbto** [Vauxoo/addons-vauxoo#1160]
Currently At module form we can see that Documentation is rendered as plain text
as shown below

<img width="1023" alt="local_modules_-_odoo - stock_account_unfuck" src="https://cloud.githubusercontent.com/assets/7598010/22051519/33ef7d2a-dd1a-11e6-82fb-8585a4135cbf.png">

The desirable look and feel would be like the one of the [README.md](https://github.com/Vauxoo/addons-vauxoo/blob/8.0/stock_account_unfuck/README.md) 
like shown below

<img width="1005" alt="addons-vauxoo_stock_account_unfuck_at_8_0_ _vauxoo_addons-vauxoo" src="https://cloud.githubusercontent.com/assets/7598010/22051534/52258d66-dd1a-11e6-8795-b1a00dee9dc7.png">

**Comment by zaoral** [comment]
you can use this tool to accomplish this 
https://github.com/vauxoo-dev/gist-vauxoo/tree/master/description2html
Will take the readme file and create the static/description/index.html from the first,

The only problem is that the script description2html works with rst, not with md files.
Best Regards
