### ISSUE TITLE
[10.0] ImportError after running ./odoo-bin 

### ISSUE THREAD

**Issue by alxolivares** [Vauxoo/addons-vauxoo#1169]
**ImportError: No module named fields**

Impacted versions:
- 10.0

Steps to reproduce:
1. run ./odoo-bin
2. open http://localhost:8069 in a browser

Current behavior:
![1](https://cloud.githubusercontent.com/assets/13812335/22378890/9665d970-e48d-11e6-847f-51a2f9b05b07.png)

Expected behavior:
 - No error message

**Comment by zaoral** [comment]
HI @alxolivares 

I think this error has been solve with https://github.com/Vauxoo/addons-vauxoo/pull/1168 merged just 15 minutes ago.

Please update addons-vauxoo and try to run your odoo server again.

Best Regards

**Comment by nhomar** [comment]
Sorry for the problem @alxolivares our bad here.

**Comment by nhomar** [comment]
closed vía https://github.com/Vauxoo/addons-vauxoo/commit/80fd767f4f1b0552da5146de1505833efbf78204

**Comment by zaoral** [comment]
Actually my fault, sorry sorry for the problems caused
Best Regards

**Comment by alxolivares** [comment]
Thanks @zaoral @nhomar , problem solved.
Greetings
