### ISSUE TITLE
[website_blog_rss] to OCA?

### ISSUE THREAD

**Issue by rafaelbn** [Vauxoo/addons-vauxoo#1184]
Hi @moylop260 @oscarolar @nhomar 

Is it possible to migrate this module to OCA? https://github.com/Vauxoo/addons-vauxoo/tree/9.0/website_blog_rss

We would like to make website_event_rss based on this one

Let me know please

cc @pedrobaeza @yajo

**Comment by moylop260** [comment]
Yes, please
+1

**Comment by pedrobaeza** [comment]
In v9 is a native feature, so no special reasons to move it.  We're abandoning v8 now.
