### ISSUE TITLE
Create Saas-17 branch

### ISSUE THREAD

**Issue by ebirbe** [Vauxoo/addons-vauxoo#1216]
Hello @nhomar, @moylop260 

I'm porting Qualifirst project to `saas-17`, but I need to have this branch for this repository. Currently I'm working with `saas-15` version of this repo, and my tests ran OK.

Could you help me creating this branch?

**Comment by moylop260** [comment]
If you use a stable version 10.0 of addons-vauxoo what are the errors raised?

**Comment by moylop260** [comment]
and what module are you usingof this project?

**Comment by ebirbe** [comment]
I'm using `saas-15` and there is no problem at all. I haven't tryed with `10.0` (is this necessary?)

About the modules, we need the `product_cost_usd` module of this project, as you can see [here](https://git.vauxoo.com/vauxoo/qualifirst/blob/saas-15/qm/__manifest__.py#L79).

**Comment by nhomar** [comment]
@ebirbe I'll take care of this.
