### ISSUE TITLE
[7.0] 'purchase_requisition_for_everybody' - Incorrect security rule

### ISSUE THREAD

**Issue by JordiBForgeFlow** [Vauxoo/addons-vauxoo#127]
In file 'ir.model.access' the security access "access_ir_filter employee" will remove to the employee the permission to delete a filter. Unfortunately this restriction will not only apply to purchase requisitions, but to all objects systemwide.

I will submit a PR with the correction.

**Comment by moylop260** [comment]
Hello @jbeficent 
Thanks for you issue.

We will wait your PR or if this one exists can you send us the link?

**Comment by JordiBForgeFlow** [comment]
@moylop260 I just submitted the PR.

**Comment by moylop260** [comment]
@jbeficent 
Thanks for you fix.
Merged
