### ISSUE TITLE
.travis.yml needs some clean up

### ISSUE THREAD

**Issue by luisg123v** [Vauxoo/addons-vauxoo#1301]
The file `.travis.yml` has some code that, AFAIK, is unnecessary. For instance, [this code to determine changed modules](https://github.com/vauxoo/addons-vauxoo/blob/12.0/.travis.yml#L41). That is natively done by MQT.

CC @moylop260

**Comment by moylop260** [comment]
+1
and also remove the https://github.com/Vauxoo/addons-vauxoo/blob/12.0/seudo_oca_dependencies.txt since that now is not needed for now since that we have removed all modules.

**Comment by luisg123v** [comment]
Fixed on https://github.com/Vauxoo/addons-vauxoo/pull/1304
