### ISSUE TITLE
default_warehouse_from_sale_team

### ISSUE THREAD

**Issue by corsisagt** [Vauxoo/addons-vauxoo#1436]
Buenas noches, quisiera pedir su apoyo en este caso, Al parecer estoy haciendo algo mal pero no logro saber que.

Tengo dos usuarios creados uno admin y otro usr, con el admin todo funciona de maravilla pero con el que tiene perfil de usuario no puedo entrar al punto de venta.

- Ya establecí el diario de venta, la bodega en el equipo de venta y el usuario.
- Ese mismo diario esta configurado en el POS y la ubicación predeterminada pertenece a la bodega del equipo de venta.
- El usuario en cuestión tiene marcado el permiso de usar todo ( filtrado por equipo de venta) y su respectivo equipo de venta predeterminado.

Pero al tratar de entrar al POS me dice:

No se ha podido completar la operación por restricciones de seguridad. Contacte por favor con su administrador de sistema.

(Tipo de documento: Journal, Operación: read) - (Registros: [2], Usuario: 11).

Estoy usando la V12 ee

Gracias.

![photo_2020-08-10_14-41-16](https://user-images.githubusercontent.com/64709846/89856411-73852f00-db56-11ea-9ffa-0e088e97519b.jpg)
![photo_2020-08-10_14-41-29](https://user-images.githubusercontent.com/64709846/89856412-741dc580-db56-11ea-82ef-6f6717158b30.jpg)
![photo_2020-08-10_14-42-17](https://user-images.githubusercontent.com/64709846/89856413-741dc580-db56-11ea-93c4-8066c4446b58.jpg)
![photo_2020-08-10_14-42-43](https://user-images.githubusercontent.com/64709846/89856415-74b65c00-db56-11ea-9bdb-a95f47f302a5.jpg)

**Comment by luisg123v** [comment]
Que tal @corsisa,

Gracias por tu reporte.

¿Podrías confirmarme que el usuario tiene suficientes permisos en el apartado Contabilidad/finanzas, por favor?

**Comment by corsisagt** [comment]
Tiene perfil "Facturacion"

**Comment by luisg123v** [comment]
Hi @WR-96,
Is this issue related to what you're currently addressing on https://github.com/Vauxoo/addons-vauxoo/pull/1437?

@CarmenMiranda,
Are you familiarized with these permissions?

**Comment by luisg123v** [comment]
This module has been heavily refactored when migrated to v14, so this is probably not an issue anymore.
