### ISSUE TITLE
[13.0] default_warehouse_from_sale_team: wrong menu on message 

### ISSUE THREAD

**Issue by suniagajose** [Vauxoo/addons-vauxoo#1476]
![Equipos Celulares - Odoo](https://user-images.githubusercontent.com/5335402/104751765-6f6bc780-571b-11eb-8d57-fa44577f0226.png)

**Comment by luisg123v** [comment]
@CarmenMiranda be aware

**Comment by suniagajose** [comment]
@luisg123v the messages are not consistent for a not technical user, this one is another example...

![Adriana Mariela Garduño Ureña - Odoo](https://user-images.githubusercontent.com/5335402/104753639-e904b500-571d-11eb-8b8e-32bbbeda2c85.png)

Message says "is an informative field" but is not readonly...

**Comment by luisg123v** [comment]
@suniagajose yes, there are a few conceptual issues on this module. Fortunately, @CarmenMiranda is already working on fixing them.

**Comment by CarmenMiranda** [comment]
> @suniagajose yes, there are a few conceptual issues on this module. Fortunately, @CarmenMiranda is already working on fixing them.

Hi, am I'm not working on it yet, depends If we are going to using it on ABSA (12.0) I will have the Go for it today, but if we are no using it, I will have to wait, at least for me to work on it :see_no_evil:

**Comment by luisg123v** [comment]
Fixed by @CarmenMiranda on #1531
