### ISSUE TITLE
[13.0] default_warehouse_from_salesteam: missing clear_cache on ir.rule

### ISSUE THREAD

**Issue by suniagajose** [Vauxoo/addons-vauxoo#1477]
Steps to reproduce:
1. Configure at less 2 salesteam and realated each one with a warehouse
2. Create transfers in both warehouses
3. Assign a user into group _Limited access to transfers (filtered by sales team)_ and select a salesteam.
4. In private mode start session with user of the step 1, without close admin session
5. Go to transfers in private mode, see transfers (all good from now)
6. With admin assign user to another salesteam.
7. Again in private mode, see transfers (nothing change) the user cannot see transfer from warehouse relate to salesteam from step 6.

Evidence on video:
https://youtu.be/5T01PpYcabg

**Comment by suniagajose** [comment]
Hi @luisg123v 

This is the issue that we talk about yesterday...

@hugho-ad suggest to me check this:

https://github.com/Vauxoo/addons-vauxoo/blob/11.0/default_warehouse_from_sale_team/models/res_users.py#L37

we not sure if the clear_cache if was forgotten do a foward-port o the clear_cache() was deprecated for any reaseon, could you check this please?

thanks,

**Comment by luisg123v** [comment]
@suniagajose I checked this with @moylop260, and this is a missing forward-port.

Be aware @CarmenMiranda

**Comment by luisg123v** [comment]
@rolandojduartem in 16.0, this is now very easy to do, thanks to https://github.com/odoo/odoo/pull/79986. In fact, the reason I submitted that change was to be abe to perform cache invalidation on this module on a clean way, but I was asked to target master and it was not possible in the previous version.

Could you help me fixing this, please?

I had forgotten this should be done during migration.

**Comment by luisg123v** [comment]
CC @desdelinux
