### ISSUE TITLE
[13.0] default_warehouse_from_salesteam: no multi-company support

### ISSUE THREAD

**Issue by suniagajose** [Vauxoo/addons-vauxoo#1511]
**Steps:**

1. Set a multi-company with a Company A and a Company B.
2. Create a sales team for Company A and assign the main warehouse.
3. Switch to company B, and create a sales team for Company B and assign the main warehouse.
4. Configure a user to display picking and picking type from assigend warehouses.
5. For user in step 4, in session with Company B assign sales team created in step 3.
6. Switch to company A and assign sales team created in step 2.
7. Switch to company B and try to create a picking (suggest: confirm a PO with stockable product)
8. [ An read error is displayed](https://drive.google.com/file/d/1xYQqS7JO1ByJUYZbypGQuWA7A98cP8uD/view?usp=sharing) because the user has as sale_team_id from company A, in companyB session.

**Current behaviour** and **expected behavoi**r explained in the following image:

https://drive.google.com/file/d/1PtYP8caAFFsxK4Wkh1zvoINWN2DgDc0l/view?usp=sharing

**Comment by luisg123v** [comment]
Fixed on #1512
