### ISSUE TITLE
[15.0] account_analytic_business_unit: pre-commit flags

### ISSUE THREAD

**Issue by rolandojduartem** [Vauxoo/addons-vauxoo#1553]
Hi, @nhomar, in the account_analytic_business_unit module appears some flags from pre-commit that I think they would be addressed to keep the code clean as possible.

**Flags (Text version):**

https://gist.github.com/rolandojduartem/dbcc36f70618f1841d2fe191ebbe743d

**Flags (Image version):**

![Screenshot from 2022-07-18 19-44-49](https://user-images.githubusercontent.com/90422721/179648236-6785ec94-18d0-4cb5-adc6-7b0d7c64e961.png)

cc @luisg123v

**Comment by luisg123v** [comment]
Fixed on #1568
