### ISSUE TITLE
[7.0] syntaxis error in three modules

### ISSUE THREAD

**Issue by moylop260** [Vauxoo/addons-vauxoo#322]
I executed 
[replace_import.py](https://github.com/Vauxoo/pylint-conf/blob/master/fix_unused_imports/replace_import.py) 7.0-addons-vauxoo all

And I saw syntaxis error in next files:

```
account_return_allowance/model/product.py
openerp_print/pyPdf/generic.py
report_profit/invoice.py
report_profit/product.py
report_profit/unit_analisys.py
```

**Comment by nhomar** [comment]
@hbto Can you fix this or deprecate such modules if they will not be used anym,ore pliz
