### ISSUE TITLE
Clean repository from not odoo modules

### ISSUE THREAD

**Issue by zaoral** [Vauxoo/addons-vauxoo#365]
The next directory list are folders in this repo that are not odoo modules and must be moved to a properly branch.

This folders are data folders, scripts and patch folders.
- account_voucher_exchange_rate_patch
- import_data_with_ids
- mrp_bom_fix_date
- mrp_fix_decimal_production
- partner_credit_limit
- product_catalog_m321
- sale_mrp_patch

**Comment by nhomar** [comment]
On Fri, Jul 24, 2015 at 8:29 PM, Katherine Zaoral [Vauxoo] <
notifications@github.com> wrote:

> he next directory list are folders in this repo that are not odoo modules
> and must be moved to a properly branch.
> 
> This folders are data folders, scripts and patch folders.
> - account_voucher_exchange_rate_patch
> - import_data_with_ids
> - mrp_bom_fix_date
> - mrp_fix_decimal_production
> - partner_credit_limit
> - product_catalog_m321
> - sale_mrp_patch
> 
> Ya removí todo ésto. en tu branch la chamba hecha.

## 

Nhomar Hernandez
CEO Vauxoo.
Site: http://vauxoo.com
Twitter: @nhomar
Blog: http://geronimo.com.ve
LPUser: http://launchpad.net/~nhomar
Odoo Gold Partner
Móvil Venezuela:
+58 4144110269
Móvil México:
+52 1 4773933942
