### ISSUE TITLE
[IMP] Png generic image of Vauxoo's logo should come from amazon s3.

### ISSUE THREAD

**Issue by nhomar** [Vauxoo/addons-vauxoo#373]
Take care I am not talking about Icon, I am talking about Logo Image.

i.e.: [image](https://github.com/Vauxoo/addons-vauxoo/blob/8.0/purchase_requisition_department/static/description/VAUXOO.png)

**Comment by zaoral** [comment]
For resolve this issue 2 PR are needed, one for every different repo: [Vauxoo/addons-vauxoo](https://github.com/Vauxoo/addons-vauxoo/) and [vauxoo-dev/gist-vauxoo](https://github.com/vauxoo-dev/gist-vauxoo).

The instance task that manage this change is  Task [vx#3900](https://www.vauxoo.com/web#id=300&view_type=form&model=project.task&action=138)  with two children task:
- Task [vx#3933](https://www.vauxoo.com/web#id=3933&view_type=form&model=project.task&action=138) for addons-vauxoo update.
- Task [vx#3934](https://www.vauxoo.com/web#id=3934&view_type=form&model=project.task&action=138) for script description2html update.

Best Regards.

**Comment by zaoral** [comment]
This issue was automactly closed when merginf pr vauxoo-dev/gist-vauxoo#20. This issuw is reopen because need that the two PR reference in the log are merged to be close.

Best Regards
