### ISSUE TITLE
Set the right user group to this button in stock inventory

### ISSUE THREAD

**Issue by josemoralesp** [Vauxoo/addons-vauxoo#39]
We need to create a new module called stock_dont_fuck_inventory which will make the job shown bellow.

The original view for stock.inventory view has this line.

``` xml
<button name="reset_real_qty" states="confirm" string="⇒ Set quantities to 0" type="object" class="oe_link oe_right" groups="stock.group_stock_user"/>
```

Should say 

``` xml
<button name="reset_real_qty" confirm='URGENT ALERT:  You will set all your lines to 0, It can not be undone. Are you sure ' states="confirm" string="⇒ Set quantities to 0" type="object" class="oe_link oe_right" groups="stock_dont_fuck_inventory.master_user"/>
```

where stock_dont_fuck_inventory will be a new module.

**Comment by nhomar** [comment]
An image with the view which we are talking about.

![alt](https://www.evernote.com/shard/s158/sh/9a1300b9-9b7a-4bef-9380-7aef1cc5d9d1/01ea043658d20d55bda976dd9c1def8b/deep/0/Ajustes-de-inventario---Odoo.png)

**Comment by nhomar** [comment]
@echeverrifm me apuntas en cual PR resolvimos esto pliz.

**Comment by echeverrifm** [comment]
@nhomar

Sera este?

https://github.com/Vauxoo/addons-vauxoo/pull/40

Federico Manuel Echeverri Choux
mobile: (+521) 444-1-400683
Tel: (+52) 444-8185539
skype: echeverrifm
twitter: @echeverrifm

2014-12-17 23:42 GMT-06:00 Nhomar Hernández [Vauxoo] <
notifications@github.com>:
