### ISSUE TITLE
website_product_filter error

### ISSUE THREAD

**Issue by antoniocanovas** [Vauxoo/addons-vauxoo#446]
I think that a dependency is missing
The error is: 
Error details:
Modelo no encontrado: product.price.ranges

Error de contexto:
Vista `product.price.ranges.form`
[view_id: 1060, xml_id: n/a, model: product.price.ranges, parent_id: n/a]" while parsing /opt/openerp/other-addons/website_product_filters/views/product_price_ranges_view.xml:4, near
<record id="product_price_ranges_form_view" model="ir.ui.view">
            <field name="name">product.price.ranges.form</field>
            <field name="model">product.price.ranges</field>
            <field name="arch" type="xml">
                <tree editable="top">
                    <field name="lower"/>
                    <field name="upper"/>
                </tree>
            </field>
        </record>

**Comment by oscarolar** [comment]
Here is the model declared https://github.com/Vauxoo/addons-vauxoo/pull/445/files#diff-ec3c3eba1423925874ec35056b0c104bR55 did you `-d databawsename -u website_product_filters`

**Comment by oscarolar** [comment]
And also, on the main code its merged https://github.com/Vauxoo/addons-vauxoo/blob/8.0/website_product_filters/models/product.py#L56

**Comment by hugho-ad** [comment]
@konerycloud could you provide some steps to reproduce the issue please

Regards

**Comment by oscarolar** [comment]
Please download the latest version, it includes some UI changes and some fixes.

**Comment by antoniocanovas** [comment]
:+1:  (install process)

**Comment by oscarolar** [comment]
How did it go?, we need to close or fix this.
