### ISSUE TITLE
website_blog_rss: produces an invalid RSS feed

### ISSUE THREAD

**Issue by gurneyalex** [Vauxoo/addons-vauxoo#449]
Hello, 

I installed website_blog_rss on the OCA instance and I get some xml at https://odoo-community.org/blog_rss.xml but there seem to be a problem as the generated RSS is not considered valid by the W3C rss feed validator, which causes several RSS parsers such as Thunderbird's to fail loading it

https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fodoo-community.org%2Fblog_rss.xml

Did I miss some configuration step?

**Comment by oscarolar** [comment]
no there is no missing configuration, the header is missing, I think I have a PR to fix this.  I'll check it out.

**Comment by gurneyalex** [comment]
@oscarolar thanks for looking into this. I did look for a PR before submitting the issue but could not find one. I'll be happy to review and test your PR.

**Comment by oscarolar** [comment]
PR here https://github.com/Vauxoo/addons-vauxoo/pull/463

**Comment by oscarolar** [comment]
@gurneyalex Alexandre, JFR, there is extra attrs used inside website builder tags that makes the W3C RSS validator to output Warning messages, but the RSS XML still valid.
