### ISSUE TITLE
website_product_availability License issue

### ISSUE THREAD

**Issue by Danisan** [Vauxoo/addons-vauxoo#461]
when present in Odoo 8 instance, causes: 
"ValueError: Wrong value for ir.module.module.license: 'LGPL-3'"

Should this be just for Odoo 9?.
Should I remove it from Odoo 8?

**Comment by moylop260** [comment]
@Danisan 
Can you give us the git sha used?
`git log -r -1`

Can you test next version: https://github.com/Vauxoo/addons-vauxoo/commit/3769e16f0fdf1caae8c1339c93f457823d6bda9d

**Comment by oscarolar** [comment]
You must update to the latest version, issue corrected.
