### ISSUE TITLE
[8.0] user_story: Black background in form view of user story

### ISSUE THREAD

**Issue by yaniaular** [Vauxoo/addons-vauxoo#468]
*\* Black background in form view of user story ***

Impacted versions:
- 8.0

Steps to reproduce:

I'm not sure. Suddenly it's happened while i was creating criterias of acceptability.

Current behavior:
- Black background in [HU 967](https://www.vauxoo.com/web?#id=967&view_type=form&model=user.story&action=726)

Expected behavior:
- White background like in [HU 928](https://www.vauxoo.com/web#id=928&view_type=form&model=user.story&menu_id=557&action=726)

**Comment by zaoral** [comment]
+1 the same happend to me

**Comment by osvalr** [comment]
I confirm that this is happening
