### ISSUE TITLE
Typo on website

### ISSUE THREAD

**Issue by osvalr** [Vauxoo/addons-vauxoo#493]
There are two typos on vauxoo website 

**sytems** must be replace to **systems**
![should be systems](https://cloud.githubusercontent.com/assets/2961943/10710929/8dc3ae1e-7a35-11e5-9ea1-425b49a981b5.png)

And the other is at the sign in buttons
![it should be "Sign in With..."](https://cloud.githubusercontent.com/assets/2961943/10710945/160ee734-7a36-11e5-8968-1a5b78f2ae1b.png)

**Comment by nhomar** [comment]
Solved in prodution.

![](http://screenshots.vauxoo.com/oem/0ac4dc-824x861.png)
