### ISSUE TITLE
Missing Partner for account entries in module stock_landed_costs

### ISSUE THREAD

**Issue by 3nodus** [Vauxoo/addons-vauxoo#502]
On creating the account entries the partner of landed costs is missing.

**Comment by hbto** [comment]
Hi @3nodus 

Could post this as an issue in Odoo proyect

https://github.com/odoo/odoo/blob/8.0/addons/stock_landed_costs/stock_landed_costs.py#L204
https://github.com/odoo/odoo/blob/8.0/addons/stock_landed_costs/stock_landed_costs.py#L118

As there is where the missing partner is,

I am basing my code on their code to create the Journal Entry & Journal Items.

Thanks for your review.

Best Regards.

**Comment by 3nodus** [comment]
Done, thank you for reply!

**Comment by hbto** [comment]
https://github.com/odoo/odoo/issues/9292
