### ISSUE TITLE
[8.0]Sequence of Landed Costs increases when clicking button "Get costs from invoice" on module stock_landed_costs_average

### ISSUE THREAD

**Issue by 3nodus** [Vauxoo/addons-vauxoo#507]
There is a problem with the sequence number... if the button "Get costs from invoice" is pressed, the sequence increases in one unit, 

Working on current document:
-->LC/2015/0024

Clicking on button "Get costs from invoice"
-->sequence increases to LC/2015/0025

**Comment by hbto** [comment]
Hi @3nodus 

That is a odoo/odoo bug,

please report there, the same happens if you push button "Compute" or "Save"
it is a problem related to the fact that name field is readonly in view and when 
reaches create method it is passed as blank,

Propose Issue and/or PR  on odoo.

Best Regards.

**Comment by hbto** [comment]
Please @3nodus  when testing the module stock_landed_costs_average,

Prior to write an issue in addons-vauxoo make sure it is not an issue in odoo core

you can make your test for odoo-core in runbot.odoo.com

Best Regards

**Comment by 3nodus** [comment]
You are right, I Just tried with the button "Get costs from invoice" following the order, but the sequence changes with the first button you press.

Thanks for your answer!

https://github.com/odoo/odoo/issues/9318
