### ISSUE TITLE
[8.0][product_lifecycl] Error in cronjob

### ISSUE THREAD

**Issue by josemoralesp** [Vauxoo/addons-vauxoo#525]
![Error](https://drive.google.com/a/vauxoo.com/file/d/0B2kzKLGF6ZvLTjF2cnd4dUZoUG8/view)

https://drive.google.com/a/vauxoo.com/file/d/0B2kzKLGF6ZvLTjF2cnd4dUZoUG8/view

I need to know the reason of this error, because it can be caused for the products imported from atrex.

**Comment by zaoral** [comment]
i will review this @josemoralesp
