### ISSUE TITLE
Unclear where procurements are selected massively

### ISSUE THREAD

**Issue by quique123** [Vauxoo/addons-vauxoo#534]
It is Unclear where procurements are selected massively.  When I go to Procurements, there is no option to Cancel procurements massively after selecting many procurements.

**Comment by moylop260** [comment]
@quique123 
You are talking about of the module:  ______
What is your sha of addons-vauxoo (`git log -r -1`): ______

**Comment by quique123** [comment]
Oh sorry, I thought this was specific to the module I was viewing.  Im talking about the Procurement Cancel module.  Ive installed it but when I go to view Procurements and select the ones I want to Cancel, I dont get a new option or button somewhere where I can cancel them.  I downloaded the module today from the community listing here: https://apps.openerp.com/apps/modules/8.0/procurement_cancel/

**Comment by quique123** [comment]
Hello?  Can you help me our with the procurement cancel module?  I am unable to use it after installed.
