### ISSUE TITLE
Error cuando intento agregar varios tags a una HU

### ISSUE THREAD

**Issue by yaniaular** [Vauxoo/addons-vauxoo#560]
https://drive.google.com/a/vauxoo.com/file/d/0B9dj_hHbN6p3clpjZHhfRlJqQzg/view?usp=drivesdk

**Comment by zaoral** [comment]
@yaniaular  this is issue is reported in https://github.com/Vauxoo/instance/issues/127

This is duplicated so I will close this issue.

Best Regards
