### ISSUE TITLE
[9.0]  - payment_term_type : error on install

### ISSUE THREAD

**Issue by mslokhat** [Vauxoo/addons-vauxoo#606]
Hi,

installing payment_term_type get this error : 

ParseError: "Invalid view definition

Error details:
Element '<xpath expr="//div/field[@name='module_product_email_template']/..">' cannot be located in parent view

Error context:
View `account.config.setting.payment.type`
[view_id: 946, xml_id: n/a, model: account.config.settings, parent_id: 535]
None" while parsing /opt/odoo/custom/addons/payment_term_type/views/account_payment_type_view.xml:17, near
<record id="view_account_config_settings_payment_type" model="ir.ui.view">
            <field name="name">account.config.setting.payment.type</field>
            <field name="model">account.config.settings</field>
            <field name="inherit_id" ref="account.view_account_config_settings"/>
            <field name="arch" type="xml">
                <xpath expr="//div/field[@name='module_product_email_template']/.." position="after">
                    <div name="payment_type">
                        <label for="payment_type"/>
                        <field name="payment_type" class="oe_inline"/>
                    </div>
                </xpath>
            </field>
        </record>

**Comment by nhomar** [comment]
Hello.

The v9.0 branch is not working yet, we are in process of migration.

If ypu share a little bit more what do you want to do, you will help us to decide which features needs more our atention.

Thanks for reporting and sorry for inconveniences.
