### ISSUE TITLE
[8.0][website_blog_rss] Problem with the date in the feed

### ISSUE THREAD

**Issue by max3903** [Vauxoo/addons-vauxoo#619]
website_blog_rss is installed on the OCA instance (version 8). A few days ago, the feed was added to Planet Python http://planetpython.org.

Today, I received a complaint from one of the planet user that he is getting spammed by our blog posts every 2 hours. The feed is pulled at this frequency, so I am suspecting that the date on each post in the feed is updated based on when the feed is requested.

You can check on the Planet: Our last post (written on Dec 30th) is always on top (Jan 5th).

Can you use the create_date field in the feed?

**Comment by nhomar** [comment]
@oscarolar can you check which should be a correct approach?

**Comment by max3903** [comment]
@oscarolar Can you reproduce? Let me know if I can help. Thanks!

FYI, website_blog_mgmt provides a publication date field:
https://github.com/OCA/website/tree/8.0/website_blog_mgmt

**Comment by max3903** [comment]
@oscarolar Any update?

**Comment by max3903** [comment]
@oscarolar @nhomar ping!

**Comment by nhomar** [comment]
@oscarolar can you include a dependency to website_blog_mgmt and include this field as proposed by @max3903 I think it is a good added value.

Regards.
