### ISSUE TITLE
icecat product uniqueness configiration

### ISSUE THREAD

**Issue by ewebhub** [Vauxoo/addons-vauxoo#635]
HI,

First of all i am very new user to odoo, 
I had install a fresh copy of odoo8 and looking match the icecat data to the magento store products
for that i had install the odoo-magento-connector and has configure it connect to odoo instillation

install the icecat product uniqueness with it 

> Included Dependencies 
> Product Image Gallery
> Products Manufacturers
> Product Information Import from icecat.
> 
> > I am not able to figure out what to mention in Icecat to OpenERP fields
> > XML Field   OpenERP Field 
> > Add an item

how will the data be mapped with store product and the icecat product uniqueness. will it create icecat product specification in magneto attributes and update in the magento store.

Please help

**Comment by nhomar** [comment]
Hello @ewebhub 

Sadly the module icecat is not mantained anymore even the dependencies should be deleted aswell.

If you need this feature in odoo v8.0 you can try your own development and/or hire some time to review the module and propose some answers.

Sorry for inconvenience I will delete the module as soon as I can at least you tell me you want help with a good PR or hiring some revision time.

Again, sorry for the inconvenience.

Regards.
