### ISSUE TITLE
oca_dependencies

### ISSUE THREAD

**Issue by esthermm** [Vauxoo/addons-vauxoo#655]
Hi, 

Im trying to use your addons-vauxoo repo, but my PR is failing because the oca_dependencies has this line "odoo-mexico-v2 git@github.com:Vauxoo/odoo-mexico-v2.git" and the system cant found it.
Any solution?

Regards.

**Comment by nhomar** [comment]
which module are you trying to use?

**Comment by esthermm** [comment]
base_user_signature_logo

**Comment by nhomar** [comment]
You can use such module without the repository you mentioned it only depends of base, sorry for the confusion, such dependency is because some unit tests only.
