### ISSUE TITLE
File not found: stock_easy_internal_transfer/wizard/stock_transfer_details.xml

### ISSUE THREAD

**Issue by luistorresm** [Vauxoo/addons-vauxoo#667]
In **openerp** the module call the file wizard/stock_transfer_details.xml

But the file was removed.
https://github.com/Vauxoo/addons-vauxoo/commit/f82906a070384f5afe9e8db31962392c2aaeef4e

**Comment by luistorresm** [comment]
@suniagajose 

Do you think that you forget delete this line?

Regards

**Comment by suniagajose** [comment]
@luistorresm you are right i forgot remove this file from manifest file

Thanks for notify
