### ISSUE TITLE
Wrong product_template changed when changing UOM for product

### ISSUE THREAD

**Issue by diggy128** [Vauxoo/addons-vauxoo#678]
In product_uom_update module, when trying to change a product's UOM, the query feeds the id from product_product though the table changed is product_template so, in line 69 in product_uom_update should be:

``` diff
-                    product_ids_validate.append(dst_product_id.id)
+                    product_ids_validate.append(dst_product_id.product_tmpl_id.id)
```

**Comment by nhomar** [comment]
@KarenKawaii take care of make a PR checking this.
