### ISSUE TITLE
[8.0][sale_team_warehouse] Problem when you want to create a sale order

### ISSUE THREAD

**Issue by ghost** [Vauxoo/addons-vauxoo#694]
I have this branch (addons-vauxoo) available. The sale_team_warehouse module is uninstalled and it has never been installed.

When I want to create a sale order, the next error appears:

![seleccion_008](https://cloud.githubusercontent.com/assets/7594736/12680995/0f450662-c672-11e5-9ce4-06013cab1d25.png)

**Comment by ghost** [comment]
This error appears only when the user belongs to a sales team

**Comment by moylop260** [comment]
@rr-clearcorp 
Thanks for report this issue.

Could you help us with a video and a description step by step to reproduce it?

**Comment by nhomar** [comment]
@moylop260 Error is clear where is:

There is a monky patch without verify instalation and cames up due to the issue on creation with static folder which load all fields.

https://github.com/Vauxoo/addons-vauxoo/blob/8.0/sale_team_warehouse/models/sales_team.py#L22

**Comment by ghost** [comment]
Attached video where the error is displayed

[issue_694.ogv.zip](https://github.com/Vauxoo/addons-vauxoo/files/112931/issue_694.ogv.zip)

**Comment by moylop260** [comment]
@dsabrinarg 
Do you have a news about this issue?

**Comment by ghost** [comment]
Thanks Nomar. Very well documented changes +1
