### ISSUE TITLE
[8.0][product_do_merge] object has no attribute 'append'

### ISSUE THREAD

**Issue by DayssamAgora** [Vauxoo/addons-vauxoo#714]
Hi i got this error when i want merge duplicate products

  File "/home/inovativ/workspace/odoo8/nec/product_do_merge/wizard/base_product_merge.py", line 535, in merge_cb
    p_ids and p_ids.append(this.product_to)
AttributeError: 'product.product' object has no attribute 'append'

**Comment by zaoral** [comment]
Hello @DayssamAgora 
Thank you for report this error.

To help you we need to know more things about the error.
1. Please list the steps you follow in the instance so we can reproduce the error you reported. This way we could be able to fix it. For future issue report you can follow this [guideline](https://github.com/Vauxoo/addons-vauxoo/blob/8.0/CONTRIBUTING.md).
2. I  review the line of the code you add in the bug report and I found that the current version has a different line content as you can see [here](https://github.com/Vauxoo/addons-vauxoo/blob/8.0/product_do_merge/wizard/base_product_merge.py#L535). This tell me that you not using the last version of the module. My first recommendation is that you update to the last version of the module. If not possible or if the error persist please supply via this issue the addons-vauxoo SH in to identify your version.

Best Regards
An thank you for contribute.

**Comment by DayssamAgora** [comment]
Hi @zaoral

Im using the same version you mentionned

`
def merge_cb(self, cr, uid, ids, context=None):

```
    assert is_integer_list(ids)

    context = dict(context or {}, active_test=False)
    this = self.browse(cr, uid, ids[0], context=context)
    p_ids = this.product_ids and this.product_ids
    p_ids and p_ids.append(this.product_to)
    product_ids = set(map(int, this.product_from and
                          [this.product_to, this.product_from] or
                          p_ids))
    if not list(product_ids):
        raise osv.except_osv(_('Error!'), _(
            """The product from must be selected for
                this option."""))
    else:
        self._merge(cr, uid, product_ids, this.product_to,
                    context=context)
    return True`
```

The error :

`Traceback (most recent call last):
  File "/home/inovativ/workspace/odoo8/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/inovativ/workspace/odoo8/openerp/http.py", line 574, in dispatch
    result = self._call_function(**self.params)
  File "/home/inovativ/workspace/odoo8/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/inovativ/workspace/odoo8/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/inovativ/workspace/odoo8/openerp/http.py", line 307, in checked_call
    return self.endpoint(*a, **kw)
  File "/home/inovativ/workspace/odoo8/openerp/http.py", line 803, in __call__
    return self.method(*args, **kw)
  File "/home/inovativ/workspace/odoo8/openerp/http.py", line 403, in response_wrap
    response = f(*args, **kw)
  File "/home/inovativ/workspace/odoo8/openerp/addons/web/controllers/main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/inovativ/workspace/odoo8/openerp/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/home/inovativ/workspace/odoo8/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/inovativ/workspace/odoo8/nec/product_do_merge/wizard/base_product_merge.py", line 531, in merge_cb
    p_ids and p_ids.append(this.product_to)
AttributeError: 'product.product' object has no attribute 'append'`

To reproduce the error :
1. Create 2 products with same name & reference .. different price & product type
2. lunch the wizard
3. select referencia
4. click on "merge with manual check"
5. click on "merge automatically"
6. confirm the wizard message
7. it shows the error

**Comment by zaoral** [comment]
@DayssamAgora thank you for report.
The issue has been confirmed.
Already working in the result at Vauxoo/addons-vauxoo#716

**Comment by DayssamAgora** [comment]
@zaoral 
@nhomar 

Thanks for your efforts
