### ISSUE TITLE
[MIG] user_story: Migrate to v9.0 

### ISSUE THREAD

**Issue by alan196** [Vauxoo/addons-vauxoo#736]
- [ ] Left installable and finished on v9.0 community.

**Comment by SaraiOsorio** [comment]
Modules to migrate to user_story
- [ ]  "sprint_kanban"
- [ ]  "project_timesheet"
- [ ]  "hr_timesheet_invoice"
- [ ]  "project_conf"
- [ ]  "report_webkit"

**Comment by SaraiOsorio** [comment]
What about the module  "hr_timesheet_invoice" in Odoo9, disappears or is renamed?

**Comment by nhomar** [comment]
> What about the module "hr_timesheet_invoice" in Odoo9, disappears or is renamed?

@SaraiOsorio I do not think we will continue managing that module as it is, we rafactor all the logic to reuse even more what is in 11.0 once I finish the technical decisions I will come back here with the result.
