### ISSUE TITLE
[9.0] controller_report_xls example

### ISSUE THREAD

**Issue by arkhan** [Vauxoo/addons-vauxoo#764]
hello..

you can help me with an example of how to use properly the module controller_report_xls

thanks..

**Comment by hbto** [comment]
Hi @arkhan 
Here you can find an example on how to use controller_report_xls

https://github.com/Vauxoo/addons-vauxoo/blob/8.0/aging_due_report/

Be aware this module has not been yet implement in v9

Regards

**Comment by arkhan** [comment]
cool thanks
