### ISSUE TITLE
[8.0] use of @api.v7 decorator 

### ISSUE THREAD

**Issue by osvalr** [Vauxoo/addons-vauxoo#765]
In some methods (please, see [here](https://github.com/Vauxoo/addons-vauxoo/commit/b0556d91b251a4df67823ad23401e5a0806e5e18#diff-d2b39316d941acce01ed5ac1aa4f0793R137)) as we can see, the use of `@api.v7` decorator restricts its use only for the old api (7.0) and currently with unittest cannot be tested throwing the following error:

``` bash
 self.quant.initializing_quant_segmentation()
   File "/odoo/openerp/api.py", line 266, in wrapper
     return new_api(self, *args, **kwargs)
 TypeError: 'NoneType' object is not callable
```

So, there are alternatives to get rid of this:
- **Define the same method**: The same method can be defined using `@api.v8` as the following example: [@api.v7](https://github.com/Vauxoo/addons-vauxoo/blob/8.0/stock_landed_costs_average/model/stock_landed_costs.py#L529) vs. [@api.v8](https://github.com/Vauxoo/addons-vauxoo/blob/8.0/stock_landed_costs_average/model/stock_landed_costs.py#L605)
  - **`NOTE`**: in this case, travis's pylint complains with the error [E0102](https://travis-ci.org/Vauxoo/addons-vauxoo/jobs/112687919#L499)
- **Remove @api.v7 decorator**: Just removing the `@api.v7` can be used in both for old and new apis.

I think this required to be discussed

**`UPDATE`**: Odoo/Odoo#10792 treats this issue in their addons

**Comment by nhomar** [comment]
@osvalr 

You need to go case by case asking for such solution. It is not an All in All out issue.

Point to the one you think you need now and make a proper PR (if aplies) or try to find a workaround on tests (if applies) ther is too much variants to threat this problem as an unique issue.

I will close this issue looking for the specific case/module and have a list of issue to delegate/fix/test.

**Comment by nhomar** [comment]
Sorry.

I did not read the title just the body.

You are talking here only about the stock_quant_cost_segmentation module right?

**Comment by osvalr** [comment]
@nhomar I began talking about `stock_quant_cost_segmentation`, but I refocused this issue rewording it because a bunch of methods (in various modules) are using `@api.v7` and this is so with this issue I'm try to establish a common rule to work with. 
- What are your comments about it the use of `@api.v(7|8)`?

**Comment by nhomar** [comment]
@osvalr I am agreed, but it is not an All in All Out issue.

We do not need to change everything there is a way to test with such elements you mentioned we just need to find such way.

But in your specific case you are absollutly right.

Try to focus in ONE module at a time (may be too if they are related) bot not all 500 Modules it will be an infinite job to fix if you see it on such way.

Reword this issue to focus on just the module you are taking care about, once you finish THAT module then you can open an issue for other one (if you find another in the middle that you NEED it, fix it also no problem).

1 Issue - 1 Module reword again this issue please.

**Comment by osvalr** [comment]
I'll close this issue and go forward to make a PR instead, to be discussed with the change in-place
