### ISSUE TITLE
[FIX] update module unit test to use action_assign method before every picking transfer operation

### ISSUE THREAD

**Issue by zaoral** [Vauxoo/addons-vauxoo#786]
module: `stock_picking_invoice_validation`

A quick fix was made here https://github.com/Vauxoo/addons-vauxoo/pull/783 to make one of our clients instance that depends of this module to work. So the unit test pass when trying to transfer a picking.

The quick fix was add a force_assign before every picking transfer.
This PR want to remove this temporal fix and make a real fix.

The real fix refers to update product demo data used in modules unit tests to have enough availability for test,  and replace the `force_assign` with  `action_assign`

**Comment by zaoral** [comment]
Hi @hugho-ad

I was looking in the history of the module and I found out that you were working on it.
Please, this is not a urgent fix. but, could you help us to make this fix?

You could follow the same steps that @yaniaular made at PR https://github.com/Vauxoo/addons-vauxoo/pull/784 to accomplish what we want.

Best Regards

**Comment by yaniaular** [comment]
@zaoral The errors are corrected. https://drive.google.com/a/vauxoo.com/file/d/0B9dj_hHbN6p3Y2hHTlh2dy1PTTA/view?usp=drivesdk
