### ISSUE TITLE
Website_Product_Filters - fix view

### ISSUE THREAD

**Issue by dolcey** [Vauxoo/addons-vauxoo#803]
I implemented the Website Products Filters module on my site, creating a view of the root of the store (/ shop) showing only categories, the trouble is that when entering each subcategory is displayed by default in list mode, which is not very suitable to my liking, I prefer grid, To accomplish this the module allows the option to remove the list view in the customize menu Website, and so the products again displayed as grid, so far everything good, the bad. .. in / shop, the root product categories under all appears a div with the "front page" of products without pager.

The original div is formatted in the template.xml view of that module:

```
           <xpath expr="//div[@id='products_grid']" position="attributes" >
                <attribute name="class">col-md-9</attribute>
           </xpath>
```

Origen:  https://github.com/Vauxoo/addons-vauxoo/blob/8.0/website_product_filters/views/templates.xml

In my view, by setting the list view in grid mode div is disabled, but disabling view mode, that is reactive, appearing also in default ppal Store page.

I have tried to hide this product result, I have overwritten the associated div, the result, the products disappear, because that div is for products in grid mode:

<xpath expr="//div[@id='products_grid']" position="replace" >
</xpath>

I appreciate any feedback you can give me a light to solve this.

Excuse my translation.

**Comment by nhomar** [comment]
Do not worry about the translation.

This module is not intended for now to be hugely generic... That is a known issue for now which we can fix when we find a free time gap.

If you absolutly need this NOW you can contact us and you can show us the error and we can fix hat for you.

sorry for the negative answer :-(
