### ISSUE TITLE
Migration accounting modules from project vauxoo/addons-vauxoo to vauxoo/account 

### ISSUE THREAD

**Issue by hbto** [Vauxoo/addons-vauxoo#932]
Moving modules from https://github.com/Vauxoo/addons-vauxoo to https://github.com/Vauxoo/account
Related to https://github.com/Vauxoo/account/issues/3
## List of modules to migrate

| Module | TODO | WIP | DONE | BLOCKED BY |
| --- | --- | --- | --- | --- |
| account_advance_payment | x |  |  |  |
| account_aged_partner_balance_vw | x |  |  |  |
| account_amortization | x |  |  |  |
| account_analytic_active_field | x |  |  |  |
| account_analytic_btree | x |  |  |  |
| account_analytic_required | x |  |  |  |
| account_anglo_saxon_missing_key | x |  |  |  |
| account_anglo_saxon_stock_move | x |  |  |  |
| account_anglo_saxon_stock_move_purchase | x |  |  |  |
| account_anglo_saxon_stock_move_sale | x |  |  |  |
| account_asset_analytic | x |  |  |  |
| account_asset_date | x |  |  |  |
| account_asset_move_check | x |  |  |  |
| account_bank_statement_vauxoo | x |  |  |  |
| account_budget_imp | x |  |  |  |
| account_closure_preparation | x |  |  |  |
| account_currency_tools | x |  |  |  |
| account_entries_report_group_by_ref | x |  |  |  |
| account_group_auditory | x |  |  |  |
| account_group_auditory_assets | x |  |  |  |
| account_invoice_line_asset_category_required | x |  |  |  |
| account_invoice_line_currency | x |  |  |  |
| account_invoice_number | x |  |  |  |
| account_invoice_regular_validation | x |  |  |  |
| account_invoice_show_by_user | x |  |  |  |
| account_invoice_supplier_quantity_attachments | x |  |  |  |
| account_invoice_tax | x |  |  |  |
| account_ledger_report | x |  |  |  |
| account_model_plans | x |  |  |  |
| account_move_cancel | x |  |  |  |
| account_move_filters | x |  |  |  |
| account_move_folio | x |  |  |  |
| account_move_group | x |  |  |  |
| account_move_line_base_tax | x |  |  |  |
| account_move_line_extended | x |  |  |  |
| account_move_line_group_analytic | x |  |  |  |
| account_move_line_group_by_asset | x |  |  |  |
| account_move_line_group_by_extend | x |  |  |  |
| account_move_line_grouping | x |  |  |  |
| account_move_line_production | x |  |  |  |
| account_move_nonzero | x |  |  |  |
| account_move_report | x |  |  |  |
| account_move_validate_multi_wizard | x |  |  |  |
| account_name_ref_search | x |  |  |  |
| account_order_wizard | x |  |  |  |
| account_payment_approve_invoice | x |  |  |  |
| account_reconcile_advance | x |  |  |  |
| account_reconcile_advance_tax | x |  |  |  |
| account_reconcile_grouping | x |  |  |  |
| account_reconcile_search | x |  |  |  |
| account_refund_early_payment | x |  |  |  |
| account_relation_move | x |  |  |  |
| account_remove_account_move_amount_field | x |  |  |  |
| account_report_general_ledger_no_journal | x |  |  |  |
| account_smart_unreconcile | x |  |  |  |
| account_tax_importation | x |  |  |  |
| account_update_amount_tax_in_move_lines | x |  |  |  |
| account_voucher_move_id | x |  |  |  |
| account_voucher_tax | x |  |  |  |
| account_voucher_tax_sat | x |  |  |  |
| account_wizard_vouchers_invoice | x |  |  |  |
| active_journal_period | x |  |  |  |
| aging_due_report | x |  |  |  |
| analytic_entry_line_group | x |  |  |  |
| analytic_entry_line_journal | x |  |  |  |
| analytic_entry_line_move | x |  |  |  |
| analytic_entry_line_partner | x |  |  |  |
| analytic_entry_line_period | x |  |  |  |
| analytic_entry_line_plans | x |  |  |  |
| analytic_entry_line_taxcode | x |  |  |  |
| analytic_plans_group | x |  |  |  |
| analytic_split_quantity | x |  |  |  |
| debit_credit_note | x |  |  |  |
| decimal_precision_currency | x |  |  |  |
| decimal_precision_tax | x |  |  |  |
| inactive_account_children | x |  |  |  |
| mrp_routing_account_journal | x |  |  |  |
| stock_deviation_account | x |  |  |  |
| stock_move_entries | x |  |  |  |
| stock_picking_show_entries_info | x |  |  |  |
| stock_purchase_analytic_plans | x |  |  |  |
| account_advance_payment | x |  |  |  |
| account_aged_partner_balance_vw | x |  |  |  |
| account_amortization | x |  |  |  |
| account_analytic_active_field | x |  |  |  |
| account_analytic_btree | x |  |  |  |
| account_analytic_required | x |  |  |  |
| account_anglo_saxon_missing_key | x |  |  |  |
| account_anglo_saxon_stock_move | x |  |  |  |
| account_anglo_saxon_stock_move_purchase | x |  |  |  |
| account_anglo_saxon_stock_move_sale | x |  |  |  |
| account_asset_analytic | x |  |  |  |
| account_asset_date | x |  |  |  |
| account_asset_move_check | x |  |  |  |
| account_bank_statement_vauxoo | x |  |  |  |
| account_budget_imp | x |  |  |  |
| account_closure_preparation | x |  |  |  |
| account_currency_tools | x |  |  |  |
| account_entries_report_group_by_ref | x |  |  |  |
| account_group_auditory | x |  |  |  |
| account_group_auditory_assets | x |  |  |  |
| account_invoice_line_asset_category_required | x |  |  |  |
| account_invoice_line_currency | x |  |  |  |
| account_invoice_number | x |  |  |  |
| account_invoice_regular_validation | x |  |  |  |
| account_invoice_show_by_user | x |  |  |  |
| account_invoice_supplier_quantity_attachments | x |  |  |  |
| account_invoice_tax | x |  |  |  |
| account_ledger_report | x |  |  |  |
| account_model_plans | x |  |  |  |
| account_move_cancel | x |  |  |  |
| account_move_filters | x |  |  |  |
| account_move_folio | x |  |  |  |
| account_move_group | x |  |  |  |
| account_move_line_base_tax | x |  |  |  |
| account_move_line_extended | x |  |  |  |
| account_move_line_group_analytic | x |  |  |  |
| account_move_line_group_by_asset | x |  |  |  |
| account_move_line_group_by_extend | x |  |  |  |
| account_move_line_grouping | x |  |  |  |
| account_move_line_production | x |  |  |  |
| account_move_nonzero | x |  |  |  |
| account_move_report | x |  |  |  |
| account_move_validate_multi_wizard | x |  |  |  |
| account_name_ref_search | x |  |  |  |
| account_order_wizard | x |  |  |  |
| account_payment_approve_invoice | x |  |  |  |
| account_reconcile_advance | x |  |  |  |
| account_reconcile_advance_tax | x |  |  |  |
| account_reconcile_grouping | x |  |  |  |
| account_reconcile_search | x |  |  |  |
| account_refund_early_payment | x |  |  |  |
| account_relation_move | x |  |  |  |
| account_remove_account_move_amount_field | x |  |  |  |
| account_report_general_ledger_no_journal | x |  |  |  |
| account_smart_unreconcile | x |  |  |  |
| account_tax_importation | x |  |  |  |
| account_update_amount_tax_in_move_lines | x |  |  |  |
| account_voucher_move_id | x |  |  |  |
| account_voucher_tax | x |  |  |  |
| account_voucher_tax_sat | x |  |  |  |
| account_wizard_vouchers_invoice | x |  |  |  |
| active_journal_period | x |  |  |  |
| aging_due_report | x |  |  |  |
| analytic_entry_line_group | x |  |  |  |
| analytic_entry_line_journal | x |  |  |  |
| analytic_entry_line_move | x |  |  |  |
| analytic_entry_line_partner | x |  |  |  |
| analytic_entry_line_period | x |  |  |  |
| analytic_entry_line_plans | x |  |  |  |
| analytic_entry_line_taxcode | x |  |  |  |
| analytic_plans_group | x |  |  |  |
| analytic_split_quantity | x |  |  |  |
| debit_credit_note | x |  |  |  |
| decimal_precision_currency | x |  |  |  |
| decimal_precision_tax | x |  |  |  |
| inactive_account_children | x |  |  |  |
| mrp_routing_account_journal | x |  |  |  |
| stock_deviation_account |  | x |  | Vauxoo/lodigroup#540 |
| stock_move_entries |  | x |  | Vauxoo/lodigroup#541 |
| stock_picking_show_entries_info | x |  |  |  |
| stock_purchase_analytic_plans | x |  |  |  |

Because of https://github.com/github-archive/task_list/issues/42
we cannot create a TODO-list inside a Table
- [ ] account_advance_payment
- [ ] account_aged_partner_balance_vw
- [ ] account_amortization
- [ ] account_analytic_active_field
- [ ] account_analytic_btree
- [ ] account_analytic_required
- [ ] account_anglo_saxon_missing_key
- [ ] account_anglo_saxon_stock_move
- [ ] account_anglo_saxon_stock_move_purchase
- [ ] account_anglo_saxon_stock_move_sale
- [ ] account_asset_analytic
- [ ] account_asset_date
- [ ] account_asset_move_check
- [ ] account_bank_statement_vauxoo
- [ ] account_budget_imp
- [ ] account_closure_preparation
- [ ] account_currency_tools
- [ ] account_entries_report_group_by_ref
- [ ] account_group_auditory
- [ ] account_group_auditory_assets
- [ ] account_invoice_line_asset_category_required
- [ ] account_invoice_line_currency
- [ ] account_invoice_number
- [ ] account_invoice_regular_validation
- [ ] account_invoice_show_by_user
- [ ] account_invoice_supplier_quantity_attachments
- [ ] account_invoice_tax
- [ ] account_ledger_report
- [ ] account_model_plans
- [ ] account_move_cancel
- [ ] account_move_filters
- [ ] account_move_folio
- [ ] account_move_group
- [ ] account_move_line_base_tax
- [ ] account_move_line_extended
- [ ] account_move_line_group_analytic
- [ ] account_move_line_group_by_asset
- [ ] account_move_line_group_by_extend
- [ ] account_move_line_grouping
- [ ] account_move_line_production
- [ ] account_move_nonzero
- [ ] account_move_report
- [ ] account_move_validate_multi_wizard
- [ ] account_name_ref_search
- [ ] account_order_wizard
- [ ] account_payment_approve_invoice
- [ ] account_reconcile_advance
- [ ] account_reconcile_advance_tax
- [ ] account_reconcile_grouping
- [ ] account_reconcile_search
- [ ] account_refund_early_payment
- [ ] account_relation_move
- [ ] account_remove_account_move_amount_field
- [ ] account_report_general_ledger_no_journal
- [ ] account_smart_unreconcile
- [ ] account_tax_importation
- [ ] account_update_amount_tax_in_move_lines
- [ ] account_voucher_move_id
- [ ] account_voucher_tax
- [ ] account_voucher_tax_sat
- [ ] account_wizard_vouchers_invoice
- [ ] active_journal_period
- [ ] aging_due_report
- [ ] analytic_entry_line_group
- [ ] analytic_entry_line_journal
- [ ] analytic_entry_line_move
- [ ] analytic_entry_line_partner
- [ ] analytic_entry_line_period
- [ ] analytic_entry_line_plans
- [ ] analytic_entry_line_taxcode
- [ ] analytic_plans_group
- [ ] analytic_split_quantity
- [ ] debit_credit_note
- [ ] decimal_precision_currency
- [ ] decimal_precision_tax
- [ ] inactive_account_children
- [ ] mrp_routing_account_journal
- [ ] stock_deviation_account
- [ ] stock_move_entries
- [ ] stock_picking_show_entries_info
- [ ] stock_purchase_analytic_plans

**Comment by nhomar** [comment]
Deployment Plan:

1.- Green all production environments (Lodigroup).
2.- Green yoytec (just adding the new repo).

---

**Comment by luisg123v** [comment]
vauxoo/account doesn't exist anymore on GitHub and the OCA repos are preferred.

I'll close this.
