### ISSUE TITLE
website_product_availability: No actual product availability in any plase.

### ISSUE THREAD

**Issue by nhomar** [Vauxoo/addons-vauxoo#992]
¿?:

![](http://screenshots.vauxoo.com/oem/d8b0c6-1795x959.png)

**Comment by oscarolar** [comment]
Nhomar FYI, still need to clean website_variant_extra,
my idea:
- [ ] use `website_variants_extra` as a placeholder for available features in public repos.
- [ ] use `website_yoytec` to insert customer features in `website_variants_extra`.
